# Generated by Django 5.1.4 on 2025-01-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='etablissement_courant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.etablissement'),
        ),
    ]
