# Generated by Django 5.0.2 on 2024-12-13 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan',
            name='redigant',
        ),
        migrations.AddField(
            model_name='bilan',
            name='redigant_laborantin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.laborantin'),
        ),
        migrations.AddField(
            model_name='bilan',
            name='redigant_radiologue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.radiologue'),
        ),
    ]
