# Generated by Django 5.1.4 on 2025-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dpi_etablissement_courant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
