# Generated by Django 5.0.2 on 2024-12-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_bilan_redigant_bilan_redigant_laborantin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
    ]
