# Generated by Django 5.1.4 on 2024-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin_user_infermier_user_laborantin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='status',
            field=models.CharField(choices=[('Oral', 'Oral'), ('Injection', 'Injection'), ('Topique', 'Topique'), ('Autre', 'Autre')], default='Oral', max_length=20),
            preserve_default=False,
        ),
    ]
