# Generated by Django 5.1.4 on 2024-12-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_medicament_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='status',
            new_name='type',
        ),
    ]
