# Generated by Django 5.1.4 on 2024-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_status_medicament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personne_a_contacter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PersonneAContacter',
        ),
    ]
