# Generated by Django 5.1.4 on 2024-12-31 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bilan_graphique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compterendu',
            name='test',
        ),
        migrations.AddField(
            model_name='compterendu',
            name='bilan',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.bilan'),
            preserve_default=False,
        ),
    ]
