# Generated by Django 5.1.4 on 2025-01-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient_personne_a_contacter_and_more'),
        ('users', '0009_remove_compterendu_test_compterendu_bilan'),
    ]

    operations = [
    ]
