# Generated by Django 5.1.4 on 2025-01-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
